name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build -t cl3mente/dualhgt:latest -t cl3mente/dualhgt:${{ github.sha }} . # $(date +%s)
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push the Docker image
      run: |
        docker push cl3mente/dualhgt:latest  # docker push dualhgt:$(date +%s)
        docker push cl3mente/dualhgt:${{ github.sha }}
